### ISSUE TITLE
Can't run openjdk.

### ISSUE THREAD

**Issue by jc-lab** [AppImage/AppImageKit#1146]
When I run the java command, I get the following error:
```
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)
```

app image builder recipe:
```
version: 1
AppDir:
...
  apt:
...
    include:
    - openjdk-11-jre-headless
AppImage:
  arch: x86_64
  update-information: guess
```

Build Machine: ubuntu:20.04
Target Machine: buster/sid
